name: project_management_muhmad_omar
description: Cactus Management app, Management tasks and employees for small company, By the developer Muhmad Omar Haj Hmdo.

publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4
  firebase_auth: ^4.2.10
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  firebase_analytics: ^10.2.0
  awesome_dialog: ^3.1.0
  firebase_storage: ^11.1.0
  loading_animation_widget: ^1.2.1


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/logo.png"


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/icon/
    - lib/images/
    - assets/lang/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700