name: project_management_muhmad_omar
description: Project management app, Management tasks and employees for small company.

publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4
  firebase_auth: ^4.2.10
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  #  get: ^4.6.5
  http: ^1.2.1
  firebase_analytics: ^10.2.0
  # elegant_notification: ^1.8.1
  # awesome_notifications_fcm: ^0.7.4+1
  awesome_notifications: ^0.9.3+1
  firebase_messaging: ^14.4.0
  awesome_dialog: ^3.1.0
  http_proxy: ^1.2.2
  responsive_builder: ^0.7.0
  font_awesome_flutter: ^10.2.1
  flutter_shapes: ^0.3.0
  provider: ^6.1.2
  flutter_feather_icons: ^2.0.0+1
  tcard: ^1.3.5
  #  fl_chart: ^0.55.2
  flutter_slidable: ^3.0.0
  table_calendar: ^3.0.8
  glassmorphism: ^3.0.0
  flutter_lints: ^4.0.0
  image_picker: ^1.1.2
  video_player: ^2.8.7
  rx_future: ^1.0.3
  firebase_storage: ^11.1.0
  android_alarm_manager_plus: ^2.1.2
  shared_preferences: ^2.1.1
  either_dart: ^0.4.0
  #  flutter_facebook_auth: ^5.0.11
  iconsax: ^0.0.8
  #  flutter_glow: ^0.3.0
  focused_menu: ^1.0.5
  searchbar_animation: ^0.0.4
  rxdart: ^0.27.7
  animated_pie_chart: ^0.0.2
  day_night_time_picker: ^1.3.1
  sizer: ^2.0.15


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/logo.png"


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/icon/
    - lib/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700